env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  "import/extensions": [".js", ".mjs", ".jsx", ".ts", ".tsx"]
  "import/parsers": {
    "@typescript-eslint/parser": [ ".ts", ".tsx" ]
  }
  "import/resolver": {
    "node": {
      "paths": ["src"],
      "extensions": [ ".js", ".jsx", ".ts", ".tsx" ]
    }
  }
rules: {
  "react/jsx-filename-extension": ['error', { "extensions": [".tsx", ".ts"] }],
  "import/extensions": [
    "error",
    "ignorePackages",
    {
      "js": "never",
      "jsx": "never",
      "ts": "never",
      "tsx": "never"
    }
  ],
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}],
  "react/require-default-props": 0,
  "react/destructuring-assignment": 0,
  "jsx-a11y/no-static-element-interactions": 0,
  "jsx-a11y/click-events-have-key-events": 0,
  no-unused-vars: off,
  no-shadow: off,
  react/no-array-index-key: off,
  semi: ["error", "never"],
  "react/jsx-props-no-spreading": off
}
